### PR TITLE
Fix MessageDecodingHelpers + More

### LINKED ISSUE #32: Data Updating
Hermes currently receives serial data, but only verifies if the data is a valid packet. The JSON packet sent by `jsonforwarder` is currently default. We need to actually update the JSON packet with data from the serial packet.

### PR DESCRIPTION
**Pull request by bill-luu**
Fixes #32 
# Changelog

- Fixed the data lengths of the decoded message (Previously, the message length constants included the metadata, however they were being used _after_ the packet was already decoded.

- Fixed a typo in KeyMotorPopulator's expecting to receive itself in it's `connect`

- Fixed the `MessageDecodingHelpers` as outlined in #32.

Check out this amazing gif to see how hermes works now:
hermesgood

### CODE REVIEW

File: CommunicationLayer/MessagingFramework/MessageDefines.cpp [hunk 1]
```diff
@@ -2,14 +2,14 @@
...
 {
-    const int BATTERY_DATA_LENGTH = 55;
-    const int BATTERY_FAULTS_DATA_LENGTH = 10;
-    const int DRIVER_CONTROLS_DATA_LENGTH = 13;
-    const int KEY_MOTOR_DATA_LENGTH = 47;
-    const int LIGHTS_DATA_LENGTH = 7;
-    const int MOTOR_DETAILS_DATA_LENGTH = 73;
-    const int MOTOR_FAULTS_DATA_LENGTH = 13;
-    const int MPPT_DATA_LENGTH = 14;
+    const int BATTERY_DATA_LENGTH = 51;
```
Comment (ExtraGravity) [inline CommunicationLayer/MessagingFramework/MessageDefines.cpp]: This doesn't match the document. A comment is probably necessary to explain why all these are 4 shorter than our docs.

File: CommunicationLayer/MessagingFramework/MessageDecodingHelpers.cpp [hunk 2]
```diff
@@ -38,12 +38,29 @@ namespace
...
+
+    dataStream >> value;
+
+    return value;
 }
 
 unsigned short MessageDecodingHelpers::getUnsignedShort(const QByteArray& data, int startIndex)
 {
-    return data.mid(startIndex, numberOfBytesInData(Type::UNSIGNED_SHORT)).toUShort();
+    unsigned short value;
```
Comment (ExtraGravity) [inline CommunicationLayer/MessagingFramework/MessageDecodingHelpers.cpp]: These should be moved closer to where they're being used.
And I'd say there is more empty lines in these functions then are necessary.

**Review by ExtraGravity — CHANGES_REQUESTED** [review]
Looks good! As an idea, we can't really tell right now which faults are fresh and which are not. What we can do it set the faults listed in the UI to be gray after like 20 seconds or something (bonus points if we can get them to fade out!)

File: CommunicationLayer/MessagingFramework/MessageDecodingHelpers.cpp [hunk 3]
```diff
@@ -53,7 +70,14 @@ unsigned char MessageDecodingHelpers::getUnsignedChar(const QByteArray& data, in
 
 unsigned int MessageDecodingHelpers::getUnsignedInt(const QByteArray& data, int startIndex)
 {
-    return data.mid(startIndex, numberOfBytesInData(Type::UNSIGNED_INT)).toUInt();
+    unsigned int value;
+
+    QDataStream dataStream(data.mid(startIndex, numberOfBytesInData(Type::UNSIGNED_INT)));
```
Comment (bseto) [inline CommunicationLayer/MessagingFramework/MessageDecodingHelpers.cpp]: The only difference between the 3 functions really... are the type of return, and then `Type::UNSIGNED_INT` `Type::UNSIGNED_SHORT` etc

There's a couple ways you could go about getting rid of the copy pasta code :P 

Using one Template to completely replace all 3 functions (hardest part would be matching the `T` value to find out what `Type::<type>` to use)

Or probably easier: make use of a helper function that uses a Template

```
//Helper function
template <class T>
T readQDataStream(QDataStream dataStream) {
   T var;
   dataStream.setByteOrder(QDataStream::LittleEndian);
   dataStream >> var;
   return var;
}
// Your normal function
unsigned int MessageDecodingHelpers::getUnsignedInt(const QByteArray& data, int startIndex) {
    QDataStream dataStream(data.mid(startIndex, numberOfBytesInData(Type::UNSIGNED_INT)));
    return readQDataStream<unsigned int>(dataStream);
}

float MessageDecodingHelpers::getFloat(const QByteArray& data, int startIndex) {
    QDataStream dataStream(data.mid(startIndex, numberOfBytesInData(Type::FLOAT)));
    return readQDataStream<float>(dataStream);
}
```

Not sure if worth it :P, and not sure if it works 100%. But could be a good opportunity to make use of your c++ knowledge.

File: CommunicationLayer/MessagingFramework/MessageDefines.cpp [hunk 4]
```diff
@@ -2,14 +2,15 @@
...
-    const int MOTOR_DETAILS_DATA_LENGTH = 73;
-    const int MOTOR_FAULTS_DATA_LENGTH = 13;
-    const int MPPT_DATA_LENGTH = 14;
+    // Message lengths do not include metadata
+    const int BATTERY_DATA_LENGTH = 51;
+    const int BATTERY_FAULTS_DATA_LENGTH = 6;
+    const int DRIVER_CONTROLS_DATA_LENGTH = 9;
+    const int KEY_MOTOR_DATA_LENGTH = 43;
+    const int LIGHTS_DATA_LENGTH = 3;
+    const int MOTOR_DETAILS_DATA_LENGTH = 69;
```
Comment (nathanaelhuh) [inline CommunicationLayer/MessagingFramework/MessageDefines.cpp]: MOTOR_DETAILS_DATA_LENGTH does not match communications protocol. Not sure which one is wrong

**Review by nathanaelhuh — CHANGES_REQUESTED** [review]

**Review by nathanaelhuh — APPROVED** [review]

**Review by ExtraGravity — APPROVED** [review]
