### PR TITLE
DataForwarded test passes reliably now

### LINKED ISSUE #60: DataForwarded Test fails occasionally
Try to run the Tests:
`for run in {1..30}; do ./Tests || break; done`

Occasionally, the `DataForwarded` Test fails

### PR DESCRIPTION
**Pull request by mglyngberg**
Fixes #60

### CODE REVIEW

File: src/Tests/BusinessLayer/JsonForwarder/JsonForwarderTest.cpp [hunk 1]
```diff
@@ -112,9 +112,9 @@ MATCHER_P2(JsonStringIs, key, value, "")
 TEST_F(JsonForwarderTest, dataForwarded)
 {
     EXPECT_CALL(*messageForwarder_, forwardData(_))
-    .Times(FORWARD_ITERATIONS);
+    .Times(AtLeast(FORWARD_ITERATIONS));
     jsonForwarder_->startForwardingData();
-    QTest::qWait(FORWARD_INTERVAL_MSEC * FORWARD_ITERATIONS + FORWARD_INTERVAL_MSEC * 0.75);
+    QTest::qWait(FORWARD_INTERVAL_MSEC * FORWARD_ITERATIONS + FORWARD_INTERVAL_MSEC);
```
Comment (bill-luu) [inline src/Tests/BusinessLayer/JsonForwarder/JsonForwarderTest.cpp]: I forgot why we changed this, was it failing with 0.75?
